### ISSUE TITLE
Planning any more data updates?

### ISSUE THREAD

**Issue by CGiattino** [mrc-ide/global-lmic-reports#5]
Hi again,

I've been showing your model estimates on [this Our World in Data page](https://ourworldindata.org/covid-models) since August 2020 and updating with the latest data every week since.

It's been about a month since your last update. Will you be publishing any more updates?

Thanks,
Charlie

**Comment by GBarnsley** [comment]
Apologies I've been adding in adjustments for Delta and Omicron variants to the outputs. Its been fairly slow due to the historic changes to the R trends. Future updates should be more regular

**Comment by CGiattino** [comment]
Ok, thanks
