### ISSUE TITLE
Recent update has 27 fewer countries than usual

### ISSUE THREAD

**Issue by CGiattino** [mrc-ide/global-lmic-reports#6]
Hi,

I'm curious why the most recent update (dated 2022-01-20) has 27 fewer countries than previous updates—and if these countries will be included again in the future?

The missing countries are: United Arab Emirates, Austria, Bahrain, Switzerland, Germany, Estonia, Hungary, Iraq, Israel, Italy, Kenya, Maldives, Malawi, Malaysia, Peru, Poland, Portugal, Romania, Serbia, Slovenia, Sweden, Chad, Turkey, Ukraine, Uruguay, United States, Venezuela.

Thanks,
Charlie

**Comment by GBarnsley** [comment]
Some countries didn't converge to fits that matched the data well enough for me feel comfortable uploading them. This is likely just a product of the MCMC method I'm using. They should be included in future updates.
